### ISSUE TITLE
Lab4 Critical - code blocks

### ISSUE THREAD

**Issue by barthba** [mbeale0/Unity3D-CodeMash-Workhop#43]
[Range(-1, 1)]
    [SerializeField] private float movementMultiplier = 0f;
    [SerializeField] private float movementRange = 7f;
    [SerializeField] private bool startMovePositive = true;

    private float startXPosition = 0f;
    private bool movingPositive = true;

above is code from lab4 finished.
below is code from lab4 as is currently:

    [Range(-1, 1)]
    [SerializeField] private float rangeOfMotion = 0f;
    [SerializeField] private float movementRange = 7f;
    [SerializeField] private bool startMovePositive = true;
    
    private float startXPosition = 0f;
    private bool movingPositive = true;

**Comment by mbeale0** [comment]
Fixed
