### ISSUE TITLE
Install Directions Suggestions

### ISSUE THREAD

**Issue by javaplus** [mbeale0/Unity3D-CodeMash-Workhop#52]
"For later projects, you can also **still** a few of the main versions directly from the hub"

I think this is supposed to be **steal**

It seems you must create a Unity account to use Unity Hub.  I didn't see this mentioned anywhere in the instructions.

It's a little confusing between step 4 and 5.  After step 4 should I go ahead and install Unity and then do something after that with step 5?  Or is Step 5 something I need to do before installing unity?  It's unclear.  WebGL was installed by default for me as was Visual Studio Community 2022.  Also, after clicking the Unity 2021.3.6 "Unity Hub" button and installing it, in unity hub it shows "2022"???  Both 2022 for the Unity version and for VS Studio???
![image](https://github.com/mbeale0/Unity3D-CodeMash-Workhop/assets/602003/c5332ac6-919e-4922-98af-106ff9334d89)

**Comment by javaplus** [comment]
Also, after the initial install (clicking the Unity Hub button and waiting forever), I went to unity hub and after going to to "add modules" and adding the WIndows support under WebGL and starting that install, it took a while... then I realized a window was out of focus that was to continue Visual studio Community ... so maybe mention this... that is watch for a VS community install pop up.

**Comment by mbeale0** [comment]
Done
